### ISSUE TITLE
Do you plan to expand the functionality of this module?

### ISSUE THREAD

**Issue by ElizarovEugene** [VeeamHub/veeam-ansible#31]
Do you plan to expand the functionality of this module?
In addition to installation, I would like to see the possibility of setting up infrastructure components. While have to make do with powershell calls:

    - name: Add vCenter
      ansible.windows.win_powershell:
        script: |
          Add-VBRvCenter -Name "vc.domain.local" -User "Administrator@vsphere.local" -Password "" -Description "Mega Lab VC"

    - name: Add Windows credentials
      ansible.windows.win_powershell:
        script: |
          Add-VBRCredentials -User ".\Administrator" -Password "Pa$$w0rd11" -Description "Veeam Windows Service Account"

    - name: Add Windows server
      ansible.windows.win_powershell:
        script: |
          Add-VBRWinServer -Name 192.168.1.24 -Description "Windows File & VMware Proxy" -Credentials (Get-VBRCredentials -name ".\Administrator") -ErrorAction Stop | Out-Null

    - name: Add Windows proxy
      ansible.windows.win_powershell:
        script: |
          Add-VBRViProxy -Server 192.168.1.24

    - name: Add Linux credentials
      ansible.windows.win_powershell:
        script: |
          Add-VBRCredentials -type Linux -User "root" -Password "Pa$$w0rd11" -Description "Veeam Linux Service Account"

    - name: Add Linux server
      ansible.windows.win_powershell:
        script: |
          Add-VBRLinux -Name 192.168.1.14 -Description "Linux VMware Proxy" -Credentials (Get-VBRCredentials -name "root") -ErrorAction Stop | Out-Null 

    - name: Add Linux proxy
      ansible.windows.win_powershell:
        script: |
          Add-VBRViLinuxProxy -Server 192.168.1.14

**Comment by carceneaux** [comment]
While this might happen down the road, I cannot provide any ETA as I have no immediate plans to do this. I'll happily accept pull requests. 😄
