### ISSUE TITLE
Playbook failed to install Veeam Backup & Replication 12 with 3 modes

### ISSUE THREAD

**Issue by shailyas** [VeeamHub/veeam-ansible#38]
Hello,
Playbook failed to install Veeam Backup & Replication 12 with 3 modes:
with remote SQL Server
or
with local Postgres
or
with remote Postgres

for example:

env:
Deployed Postgres Server version: 11
Postgres ssl auth: disabled
Pgadmin4 successfully connects to postgres server via 5432 port with below creds

connection string:
Server=bpaveeampostgres.postgres.database.azure.com;Database={your_database};Port=5432;User Id=sa@bpaveeampostgres;Password={your_password};

Veeam Backup & Replication Install with ISO Download and remote PostgreSQL (v12+):

playbook:

- name: Veeam Backup & Replication Install
  hosts: windows
  tasks:
    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: vbr_install
      vars:
        version: "12"
        iso_download: true
        sql_express_setup: false
        sql_instance: "bpaveeampostgres.postgres.database.azure.com"
        sql_username: "sa@bpaveeampostgres"
        sql_password: "XXXXXXXXX"
    - name: Applying tuning on a remote PostgreSQL server running as the VBR DB
       veeamhub.veeam.veeam_vbr_set_postgres_database_server_limits:
         os_type: Windows
         cpu_count: 16
         ram_gb: 30

I am getting error:
 "msg": "unexpected rc from 'C:\\Windows\\System32\\msiexec.exe /i G:\\Backup\\Server.x64.msi /L*V C:\\Users\\adminuser\\AppData\\Local\\Temp\\ansible-moduletmp-133221485716370249-1035159283\\msiexec.log /qn /norestart /L*v \"C:\\install\\logs\\\\BackupServer.log\" VBR_SQLSERVER_AUTHENTICATION=1 VBR_LICENSE_FILE=\"C:\\install\\vbr-license.lic\" VBR_SQLSERVER_ENGINE=\"1\" VBR_SQLSERVER_SERVER=\"bpaveeampostgres.postgres.database.azure.com\" VBR_SQLSERVER_DATABASE=\"VeeamBackup\" VBR_SQLSERVER_USERNAME=\"sa@bpaveeampostgres\" VBR_SQLSERVER_PASSWORD=\"XXXXXXXXX\" ACCEPT_LICENSING_POLICY=\"1\" ACCEPT_REQUIRED_SOFTWARE=\"1\" ACCEPT_THIRDPARTY_LICENSES=1 ACCEPTEULA=YES': see rc, stdout, and stderr for more details",
    "rc": 1603,

ps: btw Veeam 11 installed successfully with local SQL Server via playbook with 
version: "11"

**Comment by carceneaux** [comment]
I only see a playbook here with error specified for a remote Postgres install. Can you please provide more info for the failure in the other two modes listed (local Postgres/remote SQL server)?

### Remote Postgres

As shown in your error, you need to reference the log file to determine why the install failed:

`C:\install\logs\\BackupServer.log`

For a remote Postgres server, using one managed by Azure and not self-installed _might_ not be supported by Veeam.

### Remote MSSQL

Only thing different in the playbook between v11 and v12 for this variable must be specified in the playbook as shown [here](https://github.com/VeeamHub/veeam-ansible/tree/master/roles/veeam_vas#Veeam-Backup--Replication-Install-with-ISO-Download-and-remote-PostgreSQL-v12):

`sql_engine: "0" # 0-MSSQL / 1-Postgres (default)`

### Local Postgres

Are you allowing this collection to install Postgres or are you installing it yourself? If this collection is installing Postgres, the username will be `postgres` with the password being whatever was set in the `sql_password` variable during install.

**Comment by carceneaux** [comment]
Also, Veeam Backup & Replication requires at least PostgreSQL 14:

https://helpcenter.veeam.com/docs/backup/vsphere/system_requirements.html?ver=120#backup-server

![CleanShot 2023-03-01 at 09 31 35](https://user-images.githubusercontent.com/17179966/222170098-b045145c-3e9d-4528-8f4d-44f20b478549.png)

**Comment by shailyas** [comment]
Hi carceneaux,
thank you. 
After setting
sql_username: "postgres"
Veeam Backup & Replication 12 was installed with local Postgres mode

**Comment by carceneaux** [comment]
Thanks for the feedback, @shailyas!

I've updated the sample playbooks so a Postgres local install is more clear.

https://github.com/VeeamHub/veeam-ansible/tree/master/roles/veeam_vas#Veeam-Backup--Replication-Community-Edition-Install-with-ISO-Download-v12
