### ISSUE TITLE
Get-AnsibleWindowsWebRequestSpec module missing error

### ISSUE THREAD

**Issue by surdrazvan** [VeeamHub/veeam-ansible#41]
**Describe the bug**
at the Download_ISO task the playbook is failing with the message _**The term 'Get-AnsibleWindowsWebRequestSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:51 char:65**_

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
![veeam](https://user-images.githubusercontent.com/36608493/228777683-de27be21-5c6c-4d54-a35c-9e1d1c02c2b3.JPG)

My Ansible version is: 2.9.6

**Comment by carceneaux** [comment]
Howdy!

I just checked and module in error using this ansible collection: [ansible.windows](https://github.com/ansible-collections/ansible.windows)

Assuming you're using the latest version of this collection (1.4.12), the version of the ansible.windows collection uses requires ansible version: **>=2.12**

As such, I recommend upgrading ansible and ensure you're using the latest version of this collection along with its [dependencies](https://github.com/VeeamHub/veeam-ansible/blob/master/galaxy.yml).

For my part, I'll update the metadata of this collection so it requires folks to be on at least version 2.12.

Thanks for bringing this to my attention!
