### ISSUE TITLE
Custom Installation Directory?

### ISSUE THREAD

**Issue by killerclaffey** [VeeamHub/veeam-ansible#51]
Is your feature request related to a problem? Please describe.
>  Currently, the Veeam-Hub ansible module does not allow users to specify their own installation directory during installation, which may cause conflicts with existing software or custom directory structures.

Describe the solution you'd like: 
> Add a parameter to the Veeam-Hub ansible module that allows users to specify their own installation directory during installation. This will provide greater flexibility and control for users during the installation process.

Describe alternatives you've considered: 
> The only alternative is to manually install each veeam package and specify the installation directory during installation. However, this defeats the purpose of using an automated tool like ansible.

Additional context:

> This feature would be especially useful for users with custom directory structures or existing software that may conflict with the default installation directory.

**Comment by carceneaux** [comment]
Thanks for the feedback!

Additionally, pull requests are welcomed as this is an open source project.

**Comment by kbreit** [comment]
I'm interested in this enhancement and wondering if there is an ETA on when this will be merged and released.

**Comment by carceneaux** [comment]
This is now supported when leveraging the new install/upgrade process for versions 12.1 and later included in the latest release of this collection.

For older versions, 12 and below, it's still not possible to set this variable.
