### ISSUE TITLE
License path for execution environment

### ISSUE THREAD

**Issue by kbreit-insight** [VeeamHub/veeam-ansible#55]
@kbreit-insight You're most likely experiencing a different error. Please check the log specified in the error for more details.

Using the default folder it's: `C:\install\logs\BackupServer. log`

Looking at your playbook, your `source_license` parameter is most likely to blame. It needs to be a fully qualified path.

For example:

`source_license: "/root/ansible/license.lic"`

Please open a new issue if you require further assistance.

_Originally posted by @carceneaux in https://github.com/VeeamHub/veeam-ansible/issues/43#issuecomment-1731625253_
           

I am trying to understand what this should be when the playbook is run via an execution environment.

**Comment by carceneaux** [comment]
I'm sorry but I don't understand. Can you please clarify what you're trying accomplish?
