### ISSUE TITLE
Update VBR v12.1 ISO url to 12.1.2.172

### ISSUE THREAD

**Issue by matt-frankl1n** [VeeamHub/veeam-ansible#64]
Filename: VeeamBackup&Replication_12.1.2.172_20240515.iso
SHA1: 3e9e11cb8879ddeb4558ca8de702f7e821a2c25e
MD5: a12c0f6ee2faeb735c6d15d8832f915a

**Comment by carceneaux** [comment]
ISO has been updated. 😊 

Sorry for the delay. New ISOs must be tested to ensure the current collection can successfully install the newer ISO version without changes.

If you've already tested the new ISO successfully, providing a screenshot of your success with your playbook used will speed up the process.

Thanks for your feedback!
